EDATOS-5431 - Modificar la API del statistical-resources para incluir cabeceras adecuadas de Cache / LastModified / E-tag
> Corrige tests.
> Evita que los tests de core carguen los interceptores, lo que provocaba el error

[ERROR] testRetrieveByUrn(org.siemac.metamac.statistical.resources.core.dataset.repositoryimpl.DatasourceRepositoryTest)  Time elapsed: 8.806 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cacheRequestInterceptor' ...
...
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No matching bean of type [org.siemac.metamac.rest.service.cache.CacheableResourceService] found for dependency [collection of org.siemac.metamac.rest.service.cache.CacheableResourceService]: expected at least 1 bean which qualifies as autowire candidate for this dependency

dado que los tests no tienen acceso a la implementación del interceptor (StatisticalResourcesCacheableResourceServiceImpl).